enableGlobalCache: true

globalFolder: ../.yarn--three-vertex-objects

nmMode: hardlinks-global

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.2.2.cjs

npmPublishAccess: public
npmAuthToken: ${NODE_AUTH_TOKEN:-xyz123}
