packages:
  - packages/*
  - apps/*

catalog:
  '@spearwolf/eventize': ^4.0.2
  '@spearwolf/signalize': ^0.24.0
  '@types/three': ~0.181.0
  three: ~0.181.2

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - nx
  - sharp
