packages:
  - packages/*
  - apps/*
catalog:
  three: ~0.181.1
  '@types/three': ~0.181.0
  '@spearwolf/eventize': ^4.0.2
  '@spearwolf/signalize': ^0.24.0
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - nx
  - sharp
