ignore-workspace-root-check: true

packages:
  - packages/*
  - apps/*

catalog:
  '@spearwolf/eventize': ^5.0.0
  '@spearwolf/signalize': ^0.29.0
  '@types/three': ~0.183.1
  three: ~0.183.1

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - nx
  - sharp

