packages:
  - packages/*
  - apps/*

catalog:
  '@spearwolf/eventize': ^4.0.2
  '@spearwolf/signalize': ^0.25.0
  '@types/three': ~0.182.0
  three: ~0.182.0

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - nx
  - sharp
