ignore-workspace-root-check: true

packages:
  - packages/*
  - apps/*

catalog:
  '@spearwolf/eventize': ^4.0.2
  '@spearwolf/signalize': ^0.27.2
  '@types/three': ~0.183.1
  three: ~0.183.1

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - nx
  - sharp

