# https://prettier.io/docs/en/options.html
printWidth: 130
# tabWidth: 2
# useTabs: false
# semi: true
singleQuote: true
# quoteProps: "as-needed"
# jsxSingleQuote: false
trailingComma: 'all'
bracketSpacing: false
# jsxBracketSameLine: false
# arrowParens: "avoid"
endOfLine: 'lf'
