root: true

parser: "@babel/eslint-parser"
parserOptions:
  sourceType: module
  requireConfigFile: off
  babelOptions:
    presets:
      - "@babel/preset-react"

plugins:
  - prettier

extends:
  - problems
  - plugin:react/recommended
  - plugin:react/jsx-runtime

env:
  jest: true
  browser: true

settings:
  react:
    version: detect
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx

rules:
  no-fallthrough: off
  no-undef-init: off
  prefer-rest-params: off
  eqeqeq: [2, "smart"]
  no-use-before-define: off
  "react/prop-types": [1, { skipUndeclared: true }]
  "react/no-unknown-property": off
